import os
import secrets
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from google.oauth2 import id_token
from google.auth.transport import requests
from pydantic import BaseModel
from db.session import get_db
from db.models import User, APIKey

# All routes in this router are prefixed with /api/auth.
# These endpoints handle Google OAuth login and API key lifecycle management.
router = APIRouter(prefix="/api/auth", tags=["auth"])

# GOOGLE_CLIENT_ID is used to verify that incoming Google ID tokens were
# issued specifically for this application. Tokens issued for other Google
# client IDs will be rejected even if cryptographically valid.
GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")


# ── Request / Response Models ─────────────────────────────────────────────────

class GoogleLoginRequest(BaseModel):
    # Carries the Google ID token obtained by the frontend via Google OAuth.
    # The token is a signed JWT issued by Google; we verify it server-side
    # using google-auth library rather than trusting the raw payload.
    token: str


class UserResponse(BaseModel):
    id:    int
    email: str
    name:  str

    class Config:
        # from_attributes=True allows Pydantic to read values directly from
        # SQLAlchemy ORM objects (e.g., return user directly without .dict()).
        from_attributes = True


class APIKeyResponse(BaseModel):
    key:        str
    created_at: str


# ── Helper: verify Google token ───────────────────────────────────────────────

def _verify_google_token(token: str) -> dict:
    """
    Verify a Google ID token and return the decoded payload (idinfo).
    Raises HTTP 401 if the token is invalid or expired.

    idinfo contains fields such as:
      - "sub"   : Google's unique user ID (stable across sessions)
      - "email" : user's Google email address
      - "name"  : user's display name
    """
    try:
        return id_token.verify_oauth2_token(
            token, requests.Request(), GOOGLE_CLIENT_ID
        )
    except ValueError:
        raise HTTPException(status_code=401, detail="Invalid Google token")


# ── POST /api/auth/google ─────────────────────────────────────────────────────

@router.post("/google", response_model=UserResponse)
def google_login(req: GoogleLoginRequest, db: Session = Depends(get_db)):
    """
    Verify a Google ID token and return the corresponding user record.
    If the user does not exist yet, create a new record (upsert pattern).

    This is the first step of the auth flow:
      Frontend Google login → POST /api/auth/google → user record
    """
    idinfo = _verify_google_token(req.token)

    google_id = idinfo["sub"]    # Stable unique ID from Google; used as the join key
    email     = idinfo["email"]
    name      = idinfo.get("name", "")

    # Look up by google_id rather than email — email can change, google_id cannot
    user = db.query(User).filter(User.google_id == google_id).first()
    if not user:
        user = User(google_id=google_id, email=email, name=name)
        db.add(user)
        db.commit()
        db.refresh(user)  # Reload from DB to populate auto-generated fields (id, created_at)

    return user


# ── POST /api/auth/api-key ────────────────────────────────────────────────────

@router.post("/api-key", response_model=APIKeyResponse)
def create_api_key(google_token: GoogleLoginRequest, db: Session = Depends(get_db)):
    """
    Issue a new API key for the authenticated user.
    Each account is limited to one active API key at a time.

    The key is a 64-character hex string generated by secrets.token_hex(32),
    which provides 256 bits of cryptographic randomness.
    """
    idinfo = _verify_google_token(google_token.token)

    user = db.query(User).filter(User.google_id == idinfo["sub"]).first()
    if not user:
        # This can happen if the user calls /api-key before /google
        raise HTTPException(status_code=404, detail="User not found")

    # Enforce one-key-per-user limit.
    # The user must delete their existing key before generating a new one.
    existing_key = db.query(APIKey).filter(APIKey.user_id == user.id).first()
    if existing_key:
        raise HTTPException(
            status_code=400,
            detail="Each account is limited to one API key. Delete your existing key before generating a new one."
        )

    # Generate a cryptographically secure random key (256-bit entropy)
    key     = secrets.token_hex(32)
    api_key = APIKey(key=key, user_id=user.id)
    db.add(api_key)
    db.commit()
    db.refresh(api_key)

    return APIKeyResponse(key=api_key.key, created_at=str(api_key.created_at))


# ── GET /api/auth/api-keys ────────────────────────────────────────────────────

@router.get("/api-keys")
def get_api_keys(google_token: str, db: Session = Depends(get_db)):
    """
    Return all API keys belonging to the authenticated user.
    google_token is passed as a query parameter (?google_token=...).
    """
    idinfo = _verify_google_token(google_token)

    user = db.query(User).filter(User.google_id == idinfo["sub"]).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    keys = db.query(APIKey).filter(APIKey.user_id == user.id).all()
    return [APIKeyResponse(key=k.key, created_at=str(k.created_at)) for k in keys]


# ── DELETE /api/auth/api-key/{key} ───────────────────────────────────────────

@router.delete("/api-key/{key}")
def delete_api_key(key: str, google_token: str, db: Session = Depends(get_db)):
    """
    Delete a specific API key belonging to the authenticated user.
    Both the key value (path param) and google_token (query param) are required.
    Ownership is verified — a user cannot delete another user's key.
    """
    idinfo = _verify_google_token(google_token)

    user = db.query(User).filter(User.google_id == idinfo["sub"]).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    # Filter by both key value AND user_id to prevent one user from deleting
    # another user's key even if they somehow know the key string
    api_key = db.query(APIKey).filter(
        APIKey.key     == key,
        APIKey.user_id == user.id
    ).first()
    if not api_key:
        raise HTTPException(status_code=404, detail="API key not found")

    db.delete(api_key)
    db.commit()
    return {"detail": "API key deleted"}